### ISSUE TITLE
Outdated Gerber files at CardECG

### ISSUE THREAD

**Issue by Mavrikant** [RobertCsordas/MobilECG-II#4]
I believe Gerber files at [here](https://github.com/xdever/MobilECG-II/tree/master/CardECG/Hardware/gerber) are belongs to very first version of PCB design. 

I used these old gerber files and I wonder is there a critical difference between current design?
And are there critical changes in firmware? Can I use current version with old gerbers?

**Comment by RobertCsordas** [comment]
It's actually the correct version for the current firmware. I just ordered the new batch of PCBs, and will rewrite the display driver to use 8 bit, 4 wire SPI instead of 9 bit, 3 wire one currently used. You may experience problems with displays: some of them won't work in the old PCB's 9 bit mode. They are just random. I haven't any advice for choosing a working one: some of types work, some don't. They have the same type, just from different seller on ebay. Other than that, there are only price and height reducing changes in the new one.

**Comment by Mavrikant** [comment]
No. These are not same. Are we looking different files?

![image](https://cloud.githubusercontent.com/assets/7313603/24321776/9a496618-115d-11e7-94aa-08cd9891f695.png)

**Comment by RobertCsordas** [comment]
Oh! I compared our internal git repository version, and its not the same as on github :(. You had to cut traces, put in a jumper wire and add a PMOS FET like in the image attached. Sorry for image quality, it was for internal use only.

<img width="1213" alt="ecgmod" src="https://cloud.githubusercontent.com/assets/2706617/24321946/0b35410c-115a-11e7-9315-9fd4900669f5.png">

**Comment by Mavrikant** [comment]
Ok. I got it. Your image is enough. Thanks for all.

**Comment by RobertCsordas** [comment]
You welcome!
